# Generated by Django 5.0.1 on 2024-07-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataAdder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="category",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
