# Generated by Django 2.1.15 on 2024-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAdder', '0002_image_category'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='image',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
